name: Go Multi-Platform Build and Release

on:
  push:
    tags:
      - "v*" # 监听符合 vX.X.X 或 vX.X.X-beta.X 的 tag 推送
permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.goarch }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
          - os: macos-latest
            goos: darwin
            goarch: arm64
            ext: ""
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # 设置 Go 版本

      - name: Extract Version from Tag
        if: matrix.os != 'windows-latest'
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract Version from Tag
        if: matrix.os == 'windows-latest'
        run: |
          # Powershell中字符串操作需要使用-replace
          $version = $env:GITHUB_REF -replace 'refs/tags/', ''
          "VERSION=$version" | Out-File -Encoding UTF8 -FilePath $env:GITHUB_ENV

      - name: Build Binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir build
          $env:GOOS = "${{ matrix.goos }}"
          $env:GOARCH = "${{ matrix.goarch }}"
          # 确保这里使用 $env:VERSION 访问 VERSION 环境变量
          go build -ldflags="-X 'main.version=$env:VERSION'" -o "build/gocz-$env:VERSION-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}"

      - name: Build Binary (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.version=${{ env.VERSION }}'" -o build/gocz-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gocz-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/

  release:
    name: Release gocz
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/
      - name: List Downloaded Files
        run: ls -R build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*/gocz-*
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
